# Generated by Django 5.2.3 on 2025-06-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studymaterial",
            name="status",
        ),
    ]
