# Generated by Django 5.2.3 on 2025-06-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_studymaterial_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_text", models.TextField()),
                (
                    "vector_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID of the chunk in the vector database",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "embedding_provider",
                    models.CharField(
                        blank=True,
                        help_text="Embedding provider used for this chunk (e.g., 'google', 'openai')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "chunk_sequence_number",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the chunk within the document"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "study_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.studymaterial",
                    ),
                ),
            ],
            options={
                "ordering": ["study_material", "chunk_sequence_number"],
                "unique_together": {("study_material", "chunk_sequence_number")},
            },
        ),
    ]
