# Generated by Django 5.2.3 on 2025-06-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_mockexam_mockexamattempt_mockexamquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="average_mock_exam_score",
            field=models.FloatField(
                blank=True,
                help_text="Average score achieved in completed mock exams.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mock_exams_completed",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of mock exams completed by the user."
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="study_materials_uploaded_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of study materials uploaded by the user."
            ),
        ),
    ]
