# Generated by Django 5.2.3 on 2025-06-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_studygroup_studygroupmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockexamquestion",
            name="original_material_chunk",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to specific document chunk if question is derived from it",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.documentchunk",
            ),
        ),
    ]
