# Generated by Django 5.2.3 on 2025-06-18 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_mockexamquestion_original_material_chunk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID for an AI interaction session (e.g., a query-response pair).",
                    ),
                ),
                (
                    "query_text",
                    models.TextField(
                        blank=True,
                        help_text="The user's query that led to the AI response.",
                        null=True,
                    ),
                ),
                (
                    "ai_response_text",
                    models.TextField(
                        blank=True,
                        help_text="The AI's response that is being reviewed.",
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="User rating (e.g., 1-5 stars).",
                        null=True,
                    ),
                ),
                (
                    "feedback_comment",
                    models.TextField(
                        blank=True,
                        help_text="User's textual feedback or comments.",
                        null=True,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who provided the feedback. Null if anonymous.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
