# Generated by Django 5.2.3 on 2025-06-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_aifeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="aifeedback",
            name="ai_low_confidence",
            field=models.BooleanField(
                default=False,
                help_text="Flagged if AI indicated low confidence in its response.",
            ),
        ),
        migrations.AddField(
            model_name="aifeedback",
            name="context_chunks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Document chunks used as context for the AI response this feedback is for.",
                related_name="feedback_instances",
                to="core.documentchunk",
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="review_flags_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this chunk was associated with negative feedback or low AI confidence.",
            ),
        ),
    ]
